[[constraint]]
  branch = "fix-contexts-type"
  name = "github.com/atlassian/go-sentry-api"
  source = "github.com/moriyoshi/go-sentry-api"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.4"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[prune]
  go-tests = true
  unused-packages = true
