[[constraint]]
  name = "github.com/atlassian/go-sentry-api"
  revision = "728464ecc9cb871f0114a66929141c3178d6c814"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.4"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[prune]
  go-tests = true
  unused-packages = true
